[project]
name = "aur-packages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "jinja2>=3.1.4",
    "pygithub>=2.5.0",
    "tomli>=2.2.1",
    "tomli-w>=1.1.0",
]
