name: Update AUR packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  workflow_dispatch:

jobs:
  collect-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Set up dependencies'
        run: |
          uv sync --frozen --all-extras
      - name: Collect packages from target folders
        id: collect
        run: |
          uv run ./tools/collect-packages.py ./packages
    outputs:
      packages: ${{ steps.collect.outputs.packages }}
  update-package:
    needs:
      - collect-packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.collect-packages.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir ~/.ssh
          echo "${{ secrets.AUR_SSH_KEY }}" > ~/.ssh/aur_key
          chmod 400 ~/.ssh/aur_key
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  StrictHostKeyChecking=no" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur_key" >> ~/.ssh/config
          mkdir repos
          git clone ssh://aur@aur.archlinux.org/${{ matrix.package }}.git repos/${{ matrix.package }}
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Set up dependencies'
        run: |
          uv sync --frozen --all-extras
      - name: Generate package resources
        id: generate
        run: |
          uv run tools/generate-resources.py packages/${{ matrix.package }} repos/${{ matrix.package }}
      - name: Push to AUR
        run: |
          cd repos/${{ matrix.package }}
          changed=`git status -s | wc -l`
          if [ $changed = "0" ] ; then
            echo "It does not have any changes. Finished."
            exit 0
          fi
          git config user.name "${{ secrets.AUR_GIT_NAME }}"
          git config user.email "${{ secrets.AUR_GIT_EMAIL }}"
          git add .
          git commit -m "Update version to ${{ steps.generate.outputs.version }}"
          git push
