name: Check tools for management

on:
  push:
    paths:
      - 'tools/**/*.py'
  pull_request:
    paths:
      - 'tools/**/*.py'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Set up dependencies'
        run: |
          uv sync --frozen --all-extras
      - name: Lint sources
        run: |
          uvx black --check tools
