name: Check updates of dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
      - run: pipx install pipenv
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.10'
          cache: pipenv
      - run: pipenv install
      - name: Fetch version
        id: check
        run: pipenv run ./tools/fetch-latest-version.py
    outputs:
      current: ${{ steps.check.outputs.current }}
      latest: ${{ steps.check.outputs.latest }}
  create-pullrequest:
    needs: versioning
    runs-on: ubuntu-22.04
    if: needs.versioning.outputs.current != needs.versioning.outputs.latest
    steps:
      - run: pipx install pipenv
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.10'
          cache: pipenv
      - run: pipenv install
      - name: Update version in package-info
        run: pipenv run ./tools/update-version.py ${{ needs.versioning.outputs.latest }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update/package-${{ needs.versioning.outputs.latest }}
          commit-message: "Update package-info"
          title: "Update package-info from ${{ needs.versioning.outputs.current }} to ${{ needs.versioning.outputs.latest }}"
          delete-branch: true
          body: |
            > Auto-generated by GitHub Actions

            ## Refs

            - [Release page](https://github.com/firebase/firebase-tools/releases/tag/${{ needs.versioning.outputs.latest }})
