name: Check resource updates of packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  collect-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install pipenv
      - uses: actions/setup-python@v5
        with:
          architecture: x64
          python-version: '3.10'
          cache: pipenv
      - run: pipenv install
      - name: Collect packages from target folders
        id: collect
        run: |
          pipenv run ./tools/collect-packages.py ./packages
    outputs:
      packages: ${{ steps.collect.outputs.packages }}
  check-package:
    needs:
      - collect-packages
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.collect-packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Set up dependencies'
        run: |
          uv sync --frozen --all-extras
      - name: Try update version
        id: updating
        run: |
          uv run ./tools/try-update-sources.py packages/${{ matrix.package }}
      - name: Create Pull Request
        if: steps.updating.outputs.current != steps.updating.outputs.latest
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update/${{ matrix.package }}/${{ steps.updating.outputs.latest }}
          commit-message: "Update package-info of ${{ matrix.package }}"
          title: "Update package-info of ${{ matrix.package }} from ${{ steps.updating.outputs.current }} to ${{ steps.updating.outputs.latest }}"
          delete-branch: true
          body: |
            *Auto-generated by GitHub Actions*
