name: Check tools for management

on:
  push:
    paths:
      - 'tools/**/*.py'
  pull_request:
    paths:
      - 'tools/**/*.py'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install pipenv
      - uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.10'
          cache: pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Lint sources
        run: |
          pipenv run black --check tools
