name: Update version of firebase-tools

on:
  workflow_dispatch:

jobs:
  fetch-latest-version:
    runs-on: ubuntu-latest
    steps:
      - id: check_latest
        run: |
          version=`curl https://api.github.com/repos/firebase/firebase-tools/releases|jq '.[0].name[1:]'`
          echo "::set-output name=latest_version::${version}"
  update-deps:
    needs: fetch-latest-version
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo pacman -Sy --noconfirm pacman-contrib
          sed -i -e "s/pkgver=.*/pkgver=${{ steps.check_latest.outputs.latest_version }}/g" PKGBUILD
          makepkg --skipchecksums
          updpkgsums
          makepkg --printsrcinfo > .SRCINFO
          git status
